apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hbapi
  name: hbapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hbapi
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hbapi
    spec:
      containers:
      - image: ts01soonr/hbapi:latest
        name: hbapi
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hbapi
spec:
  type: NodePort
  selector:
    app: hbapi
  ports:
    - nodePort: 32000
      port: 80
      targetPort: 80

