apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hbc
  name: hbc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hbc
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hbc
    spec:
      containers:
      - image: ts01soonr/jre8:latest
        name: hbc
        imagePullPolicy: Always
        ports:
        - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: hbclient
spec:
  type: NodePort
  selector:
    app: hbc
  ports:
    - nodePort: 32108
      port: 8888
      targetPort: 8888

