kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: ./shared
    containerPath: /tmp/shared
- role:  worker
  extraMounts:
  - hostPath: ./shared
    containerPath: /tmp/shared
- role:  worker
  extraMounts:
  - hostPath: ./shared
    containerPath: /tmp/shared

